name: Check ATBPServer Formatting

on:
  push:
    branches: [ "master" ]
    paths:
    - ATBPServer/**.js
    - .github/workflows/format-server.yml
  pull_request:
    branches: [ "master" ]
    paths:
    - ATBPServer/**.js
    - .github/workflows/format-server.yml

permissions:
  contents: read

jobs:
  format-server:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './ATBPServer'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm pkg delete scripts.postinstall && npm install
    - name: Execute Prettier check
      run: npx prettier . --check
